version: "3.4"

services:
  you-movie:
    image: you-movie
    build:
      dockerfile: Dockerfile
    depends_on:
      - you-movie.mongo.database
    ports:
      - 3000:3000

  you-movie.mongo.database:
    image: mongo:4.4
    restart: always
    ports:
      - 27017:27017